name: Create Release
run-name: Creating Release

on:
  push:
    branches:
      - main
    paths:
      - '**.pre-commit-hooks.yaml'

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Check Commit for Release
        id: check_commit
        run: |
          # Checking Last Commit
          COMMIT_MSG=$(git --no-pager log -1 --pretty=%B)
          if [[ "${COMMIT_MSG}" =~ Release\ v([0-9]+\.[0-9]+\.[0-9]+) ]]; then
            echo "VERSION=${BASH_REMATCH[1]}" >> "${GITHUB_ENV}"
          else
            echo "Not a release commit."
            exit 0
          fi

      - name: Create Tag and Release for ${{ env.VERSION }}
        id: create-tag
        if: ${{ env.VERSION != '' }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          TAG="v${VERSION}"

          git config user.name "GitHub Actions"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git tag -a "${TAG}" -m "Release ${VERSION}"
          git push origin "${TAG}"
          gh release create "${TAG}" --notes-from-tag
